default: &dev_and_test
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DATABASE_DEV_USERNAME'] %>
  password: <%= ENV['DATABASE_DEV_PASSWORD'] %>
  host: <%= ENV['DATABASE_DEV_URL'] %>
  port: <%= ENV['DATABASE_DEV_PORT'] %>

development:
  <<: *dev_and_test
  database: knoll_development

test:
  <<: *dev_and_test
  database: knoll_test

production:
  database: knoll_production
  username: knoll
  password: <%= ENV["KNOLL_DATABASE_PASSWORD"] %>
